INCLUDEPATH+= \
$$PWD/../esp-idf/components/app_trace/include \
$$PWD/../esp-idf/components/app_trace/port/include \
$$PWD/../esp-idf/components/app_update/include \
$$PWD/../esp-idf/components/bootloader_support/include \
$$PWD/../esp-idf/components/bootloader_support/bootloader_flash/include \
$$PWD/../esp-idf/components/bt/esp_ble_mesh/lib/include \
$$PWD/../esp-idf/components/bt/esp_ble_mesh/api/core/include \
$$PWD/../esp-idf/components/bt/esp_ble_mesh/api/models/include \
$$PWD/../esp-idf/components/bt/esp_ble_mesh/btc/include \
$$PWD/../esp-idf/components/bt/esp_ble_mesh/common/include \
$$PWD/../esp-idf/components/bt/esp_ble_mesh/common/tinycrypt/include \
$$PWD/../esp-idf/components/bt/esp_ble_mesh/core/include \
$$PWD/../esp-idf/components/bt/esp_ble_mesh/models/client/include \
$$PWD/../esp-idf/components/bt/esp_ble_mesh/models/common/include \
$$PWD/../esp-idf/components/bt/esp_ble_mesh/models/server/include \
$$PWD/../esp-idf/components/bt/esp_ble_mesh/v1.1/api/core/include \
$$PWD/../esp-idf/components/bt/esp_ble_mesh/v1.1/api/models/include \
$$PWD/../esp-idf/components/bt/esp_ble_mesh/v1.1/btc/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/babblesim/core/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/babblesim/edtt/hci_transport/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/babblesim/hw/bsp/nrf52_bsim/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/babblesim/hw/mcu/nordic/nrf52_bsim/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/ext/tinycrypt/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/nimble/controller/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/nimble/drivers/dialog_cmac/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/nimble/drivers/native/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/nimble/drivers/nrf51/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/nimble/drivers/nrf52/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/nimble/drivers/nrf5340/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/nimble/host/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/nimble/host/mesh/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/nimble/host/services/ans/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/nimble/host/services/bas/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/nimble/host/services/bleuart/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/nimble/host/services/cts/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/nimble/host/services/dis/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/nimble/host/services/gap/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/nimble/host/services/gatt/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/nimble/host/services/hid/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/nimble/host/services/hr/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/nimble/host/services/htp/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/nimble/host/services/ias/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/nimble/host/services/ipss/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/nimble/host/services/lls/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/nimble/host/services/prox/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/nimble/host/services/sps/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/nimble/host/services/tps/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/nimble/host/store/config/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/nimble/host/store/ram/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/nimble/host/util/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/nimble/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/nimble/transport/common/hci_h4/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/nimble/transport/dialog_cmac/cmac_driver/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/nimble/transport/emspi/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/nimble/transport/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/nimble/transport/socket/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/porting/examples/linux/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/porting/examples/linux_blemesh/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/porting/examples/nuttx/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/porting/nimble/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/porting/npl/dummy/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/porting/npl/freertos/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/porting/npl/linux/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/porting/npl/mynewt/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/porting/npl/nuttx/include \
$$PWD/../esp-idf/components/bt/host/nimble/nimble/porting/npl/riot/include \
$$PWD/../esp-idf/components/bt/host/nimble/esp-hci/include \
$$PWD/../esp-idf/components/bt/host/nimble/port/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/api/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/bta/ar/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/bta/av/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/bta/dm/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/bta/gatt/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/bta/hd/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/bta/hf_ag/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/bta/hf_client/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/bta/hh/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/bta/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/bta/jv/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/bta/sdp/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/bta/sys/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/btc/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/btc/profile/esp/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/btc/profile/std/a2dp/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/btc/profile/std/battery/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/btc/profile/std/dis/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/btc/profile/std/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/btc/profile/std/smp/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/common/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/device/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/external/sbc/decoder/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/external/sbc/encoder/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/external/sbc/plc/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/hci/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/stack/a2dp/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/stack/avct/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/stack/avdt/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/stack/avrc/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/stack/btm/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/stack/gap/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/stack/gatt/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/stack/hid/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/stack/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/stack/l2cap/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/stack/rfcomm/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/stack/sdp/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/stack/smp/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/config/include \
$$PWD/../esp-idf/components/bt/common/api/include \
$$PWD/../esp-idf/components/bt/common/btc/include \
$$PWD/../esp-idf/components/bt/common/btc/profile/esp/blufi/include \
$$PWD/../esp-idf/components/bt/common/btc/profile/esp/include \
$$PWD/../esp-idf/components/bt/common/include \
$$PWD/../esp-idf/components/bt/common/osi/include \
$$PWD/../esp-idf/components/bt/include \
$$PWD/../esp-idf/components/bt/include/esp32/include \
$$PWD/../esp-idf/components/bt/include/esp32c3/include \
$$PWD/../esp-idf/components/bt/include/esp32c2/include \
$$PWD/../esp-idf/components/bt/include/esp32c6/include \
$$PWD/../esp-idf/components/bt/include/esp32h2/include \
$$PWD/../esp-idf/components/bt/include/esp32h4/include \
$$PWD/../esp-idf/components/bt/porting/ext/tinycrypt/include \
$$PWD/../esp-idf/components/bt/porting/include \
$$PWD/../esp-idf/components/bt/porting/nimble/include \
$$PWD/../esp-idf/components/bt/porting/npl/freertos/include \
$$PWD/../esp-idf/components/bt/porting/transport/include \
$$PWD/../esp-idf/components/driver/include \
$$PWD/../esp-idf/components/driver/analog_comparator/include \
$$PWD/../esp-idf/components/driver/dac/include \
$$PWD/../esp-idf/components/driver/gpio/include \
$$PWD/../esp-idf/components/driver/gptimer/include \
$$PWD/../esp-idf/components/driver/i2c/include \
$$PWD/../esp-idf/components/driver/i2s/include \
$$PWD/../esp-idf/components/driver/deprecated/driver \
$$PWD/../esp-idf/components/driver/ledc/include \
$$PWD/../esp-idf/components/driver/mcpwm/include \
$$PWD/../esp-idf/components/driver/parlio/include \
$$PWD/../esp-idf/components/driver/pcnt/include \
$$PWD/../esp-idf/components/driver/rmt/include \
$$PWD/../esp-idf/components/driver/sdio_slave/include \
$$PWD/../esp-idf/components/driver/sdmmc/include \
$$PWD/../esp-idf/components/driver/sigma_delta/include \
$$PWD/../esp-idf/components/driver/spi/include \
$$PWD/../esp-idf/components/driver/temperature_sensor/include \
$$PWD/../esp-idf/components/driver/test_apps/components/esp_serial_slave_link/include \
$$PWD/../esp-idf/components/driver/test_apps/components/test_driver_utils/include \
$$PWD/../esp-idf/components/driver/test_apps/legacy_rmt_driver/components/infrared_tools/include \
$$PWD/../esp-idf/components/driver/touch_sensor/esp32/include \
$$PWD/../esp-idf/components/driver/touch_sensor/esp32s2/include \
$$PWD/../esp-idf/components/driver/touch_sensor/esp32s3/include \
$$PWD/../esp-idf/components/driver/touch_sensor/include \
$$PWD/../esp-idf/components/driver/twai/include \
$$PWD/../esp-idf/components/driver/uart/include \
$$PWD/../esp-idf/components/driver/usb_serial_jtag/include \
$$PWD/../esp-idf/components/esp_coex/include \
$$PWD/../esp-idf/components/esp_event/include \
$$PWD/../esp-idf/components/esp_http_client/include \
$$PWD/../esp-idf/components/esp_http_client/lib/include \
$$PWD/../esp-idf/components/esp_http_server/include \
$$PWD/../esp-idf/components/esp_https_ota/include \
$$PWD/../esp-idf/components/usb/include \
$$PWD/../esp-idf/components/xtensa/esp32/include \
$$PWD/../esp-idf/components/xtensa/esp32s2/include \
$$PWD/../esp-idf/components/xtensa/esp32s3/include \
$$PWD/../esp-idf/components/xtensa/include \
$$PWD/../esp-idf/components/esp_app_format/include \
$$PWD/../esp-idf/components/esp_mm/include \
$$PWD/../esp-idf/components/esp_mm/test_apps/components/test_mm_utils/include \
$$PWD/../esp-idf/components/esp_psram/include \
$$PWD/../esp-idf/components/esp_phy/esp32/include \
$$PWD/../esp-idf/components/esp_phy/esp32c3/include \
$$PWD/../esp-idf/components/esp_phy/esp32h2/include \
$$PWD/../esp-idf/components/esp_phy/esp32s2/include \
$$PWD/../esp-idf/components/esp_phy/esp32s3/include \
$$PWD/../esp-idf/components/esp_phy/include \
$$PWD/../esp-idf/components/esp_phy/esp32c2/include \
$$PWD/../esp-idf/components/esp_phy/esp32c6/include \
$$PWD/../esp-idf/components/esp_phy/esp32h4/include \
$$PWD/../esp-idf/components/esp_ringbuf/include \
$$PWD/../esp-idf/components/esp_wifi/include \
$$PWD/../esp-idf/components/esp_wifi/wifi_apps/include \
$$PWD/../esp-idf/components/espcoredump/include \
$$PWD/../esp-idf/components/esptool_py/esptool/flasher_stub/include \
$$PWD/../esp-idf/components/freertos/FreeRTOS-Kernel-SMP/include \
$$PWD/../esp-idf/components/freertos/FreeRTOS-Kernel-SMP/portable/linux/include \
$$PWD/../esp-idf/components/freertos/FreeRTOS-Kernel-SMP/portable/riscv/include \
$$PWD/../esp-idf/components/freertos/FreeRTOS-Kernel-SMP/portable/xtensa/include \
$$PWD/../esp-idf/components/freertos/FreeRTOS-Kernel/include \
$$PWD/../esp-idf/components/freertos/FreeRTOS-Kernel/portable/linux/include \
$$PWD/../esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/include \
$$PWD/../esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include \
$$PWD/../esp-idf/components/freertos/config/include \
$$PWD/../esp-idf/components/freertos/config/linux/include \
$$PWD/../esp-idf/components/freertos/config/riscv/include \
$$PWD/../esp-idf/components/freertos/config/xtensa/include \
$$PWD/../esp-idf/components/freertos/esp_additions/include \
$$PWD/../esp-idf/components/heap/include \
$$PWD/../esp-idf/components/idf_test/include \
$$PWD/../esp-idf/components/log/include \
$$PWD/../esp-idf/components/lwip/include \
$$PWD/../esp-idf/components/lwip/lwip/src/include \
$$PWD/../esp-idf/components/lwip/port/esp32xx/include \
$$PWD/../esp-idf/components/lwip/port/freertos/include \
$$PWD/../esp-idf/components/lwip/port/include \
$$PWD/../esp-idf/components/lwip/port/linux/include \
$$PWD/../esp-idf/components/mbedtls/mbedtls/3rdparty/everest/include \
$$PWD/../esp-idf/components/mbedtls/mbedtls/include \
$$PWD/../esp-idf/components/mbedtls/mbedtls/tests/include \
$$PWD/../esp-idf/components/mbedtls/port/include \
$$PWD/../esp-idf/components/mbedtls/port/aes/dma/include \
$$PWD/../esp-idf/components/mbedtls/port/sha/dma/include \
$$PWD/../esp-idf/components/mbedtls/esp_crt_bundle/include \
$$PWD/../esp-idf/components/mqtt/esp-mqtt/host_test/mocks/include \
$$PWD/../esp-idf/components/mqtt/esp-mqtt/include \
$$PWD/../esp-idf/components/mqtt/esp-mqtt/lib/include \
$$PWD/../esp-idf/components/mqtt/test_apps/common/include \
$$PWD/../esp-idf/components/nvs_flash/include \
$$PWD/../esp-idf/components/openthread/openthread/include \
$$PWD/../esp-idf/components/openthread/openthread/src/posix/platform/include \
$$PWD/../esp-idf/components/openthread/openthread/third_party/mbedtls/repo/3rdparty/everest/include \
$$PWD/../esp-idf/components/openthread/openthread/third_party/mbedtls/repo/include \
$$PWD/../esp-idf/components/openthread/openthread/third_party/mbedtls/repo/tests/include \
$$PWD/../esp-idf/components/openthread/include \
$$PWD/../esp-idf/components/protocomm/include \
$$PWD/../esp-idf/components/pthread/include \
$$PWD/../esp-idf/components/sdmmc/include \
$$PWD/../esp-idf/components/sdmmc/test_apps/sdmmc_console/components/sdmmc_test_board/include \
$$PWD/../esp-idf/components/soc/esp32/include \
$$PWD/../esp-idf/components/soc/include \
$$PWD/../esp-idf/components/soc/esp32c3/include \
$$PWD/../esp-idf/components/soc/esp32h2/include \
$$PWD/../esp-idf/components/soc/esp32s2/include \
$$PWD/../esp-idf/components/soc/esp32s3/include \
$$PWD/../esp-idf/components/soc/esp32c2/include \
$$PWD/../esp-idf/components/soc/esp32c6/include \
$$PWD/../esp-idf/components/soc/esp32p4/include \
$$PWD/../esp-idf/components/soc/linux/include \
$$PWD/../esp-idf/components/spi_flash/include \
$$PWD/../esp-idf/components/spi_flash/test_apps/components/test_flash_utils/include \
$$PWD/../esp-idf/components/spi_flash/sim/stubs/soc/include \
$$PWD/../esp-idf/components/spiffs/include \
$$PWD/../esp-idf/components/tcp_transport/include \
$$PWD/../esp-idf/components/ulp/ulp_riscv/include \
$$PWD/../esp-idf/components/ulp/ulp_riscv/shared/include \
$$PWD/../esp-idf/components/ulp/ulp_riscv/ulp_core/include \
$$PWD/../esp-idf/components/ulp/lp_core/include \
$$PWD/../esp-idf/components/ulp/lp_core/lp_core/include \
$$PWD/../esp-idf/components/ulp/lp_core/shared/include \
$$PWD/../esp-idf/components/ulp/ulp_common/include \
$$PWD/../esp-idf/components/ulp/ulp_fsm/include \
$$PWD/../esp-idf/components/unity/include \
$$PWD/../esp-idf/components/vfs/include \
$$PWD/../esp-idf/components/wear_levelling/include \
$$PWD/../esp-idf/components/wifi_provisioning/include \
$$PWD/../esp-idf/components/wpa_supplicant/port/include \
$$PWD/../esp-idf/components/wpa_supplicant/esp_supplicant/include \
$$PWD/../esp-idf/components/wpa_supplicant/include \
$$PWD/../esp-idf/components/asio/asio/asio/include \
$$PWD/../esp-idf/components/coap/libcoap/include \
$$PWD/../esp-idf/components/libsodium/libsodium/src/libsodium/include \
$$PWD/../esp-idf/components/nvs_sec_provider/include \
$$PWD/../esp-idf/components/efuse/esp32/include \
$$PWD/../esp-idf/components/efuse/esp32c3/include \
$$PWD/../esp-idf/components/efuse/esp32h2/include \
$$PWD/../esp-idf/components/efuse/esp32s2/include \
$$PWD/../esp-idf/components/efuse/esp32s3/include \
$$PWD/../esp-idf/components/efuse/include \
$$PWD/../esp-idf/components/efuse/esp32c2/include \
$$PWD/../esp-idf/components/efuse/esp32c6/include \
$$PWD/../esp-idf/components/efuse/esp32p4/include \
$$PWD/../esp-idf/components/efuse/test_apps/main/one_key_block/include \
$$PWD/../esp-idf/components/efuse/test_apps/main/three_key_blocks/include \
$$PWD/../esp-idf/components/efuse/test_apps/main/with_key_purposes/include \
$$PWD/../esp-idf/components/esp_common/include \
$$PWD/../esp-idf/components/esp_eth/include \
$$PWD/../esp-idf/components/esp_gdbstub/include \
$$PWD/../esp-idf/components/esp_gdbstub/src/port/riscv/include \
$$PWD/../esp-idf/components/esp_gdbstub/src/port/xtensa/include \
$$PWD/../esp-idf/components/esp_gdbstub/test_gdbstub_host/rv_decode/include \
$$PWD/../esp-idf/components/esp_hid/include \
$$PWD/../esp-idf/components/esp_https_server/include \
$$PWD/../esp-idf/components/esp_hw_support/include \
$$PWD/../esp-idf/components/esp_hw_support/port/include \
$$PWD/../esp-idf/components/esp_lcd/include \
$$PWD/../esp-idf/components/esp_local_ctrl/include \
$$PWD/../esp-idf/components/esp_netif/include \
$$PWD/../esp-idf/components/esp_netif/linux/stubs/include \
$$PWD/../esp-idf/components/esp_pm/include \
$$PWD/../esp-idf/components/esp_rom/include \
$$PWD/../esp-idf/components/esp_system/include \
$$PWD/../esp-idf/components/esp_system/port/include \
$$PWD/../esp-idf/components/esp_timer/include \
$$PWD/../esp-idf/components/hal/esp32/include \
$$PWD/../esp-idf/components/hal/esp32c3/include \
$$PWD/../esp-idf/components/hal/esp32h2/include \
$$PWD/../esp-idf/components/hal/esp32s2/include \
$$PWD/../esp-idf/components/hal/esp32s3/include \
$$PWD/../esp-idf/components/hal/include \
$$PWD/../esp-idf/components/hal/platform_port/include \
$$PWD/../esp-idf/components/hal/esp32c2/include \
$$PWD/../esp-idf/components/hal/esp32c6/include \
$$PWD/../esp-idf/components/hal/esp32p4/include \
$$PWD/../esp-idf/components/ieee802154/include \
$$PWD/../esp-idf/components/ieee802154/test_apps/test_ieee802154/main/include \
$$PWD/../esp-idf/components/linux/include \
$$PWD/../esp-idf/components/perfmon/include \
$$PWD/../esp-idf/components/riscv/include \
$$PWD/../esp-idf/components/touch_element/include \
$$PWD/../esp-idf/components/esp_adc/deprecated/include \
$$PWD/../esp-idf/components/esp_adc/esp32/include \
$$PWD/../esp-idf/components/esp_adc/esp32c2/include \
$$PWD/../esp-idf/components/esp_adc/esp32c3/include \
$$PWD/../esp-idf/components/esp_adc/esp32c6/include \
$$PWD/../esp-idf/components/esp_adc/esp32h2/include \
$$PWD/../esp-idf/components/esp_adc/esp32p4/include \
$$PWD/../esp-idf/components/esp_adc/esp32s2/include \
$$PWD/../esp-idf/components/esp_adc/esp32s3/include \
$$PWD/../esp-idf/components/esp_adc/include \
$$PWD/../esp-idf/components/esp_bootloader_format/include \
$$PWD/../esp-idf/components/esp_partition/include \
$$PWD/../esp-idf/components/bt/host/bluedroid/api/include/api \
$$PWD/../esp-idf/components/driver/deprecated
